# Generated by Django 3.2.5 on 2021-07-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Event name')),
                ('description', models.TextField(verbose_name='Event description')),
                ('date_from', models.DateField(verbose_name='Event date start')),
                ('date_to', models.DateField(verbose_name='Event date end')),
                ('location_name', models.CharField(blank=True, default='', max_length=120)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Event longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Event latitude')),
            ],
        ),
    ]
