# Generated by Django 3.2.4 on 2021-07-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zlecenia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zlecenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True)),
                ('czas', models.IntegerField(verbose_name='Liczba dni przeznaczona na zlecenie:')),
            ],
        ),
        migrations.DeleteModel(
            name='Zlecenia',
        ),
    ]
