# Generated by Django 3.2.5 on 2021-07-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zlecenia', '0003_eventemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('n', 'Note'), ('a', 'Accident')], default='n', max_length=1)),
                ('description', models.TextField(verbose_name='Note')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Zlecenia.employee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zlecenia.event')),
            ],
        ),
    ]
